# Generated by Django 3.1.6 on 2021-02-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressevents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressevent',
            old_name='button_state',
            new_name='is_button_on',
        ),
    ]
